name: msal_js_web_example
description: 'Vanilla web example for MSAL.js using package:msal_js.'
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  msal_js: ^2.14.0-pre.1

dev_dependencies:
  build_runner: ^2.0.4
  build_web_compilers: ^3.0.0
  lints: ^1.0.1

dependency_overrides:
  msal_js:
    path: ../../
